services:
  postgres:
    image: postgres:15
    container_name: postgres-eventsdb
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: eventdbuser
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network:
    driver: bridge